### ISSUE TITLE
Powershell script doesn't complete successfully reliably

### ISSUE THREAD

**Issue by timheuer** [MicrosoftDocs/cloud-developer-advocates#310]
When using the powershell script, the TOC.yml file doesn't consistently generate correctly.  It fails to put the 'name' attribute value in the first child node in the items group.  This blank value breaks the TOC rendering on the site.

**Comment by glaucia86** [comment]
Same thing happen to me. I opened a PR here and are saying have a problem with the tag `name`

cc: @timheuer

**Comment by MaximRouiller** [comment]
@glaucia86 @timheuer fixed :)
