### ISSUE TITLE
Verb-Noun-Noun is not a PowerShell Naming convention

### ISSUE THREAD

**Issue by kilasuit** [MicrosoftDocs/cloud-developer-advocates#334]
Considering you have some pretty well versed PowerShell people I cannot fathom who would think this was an acceptable name for a function

https://github.com/MicrosoftDocs/cloud-developer-advocates/blob/c301c0650bcb4de35fd277d0ab3407e20264d18a/FromYmlToTOC-INDEX.ps1#L217

Please rename to one that fits PowerShell Standards of Verb-Noun

**Comment by vexx32** [comment]
Is `Format-` even the appropriate verb here? Format is for display formatting primarily (e.g., Format-Table,  Format-Hex)

Sounds like it might be better suited for ConvertTo-*?

**Comment by corbob** [comment]
I would say `Convert` is probably the more appropriate verb to use here. https://docs.microsoft.com/en-us/powershell/developer/cmdlet/approved-verbs-for-windows-powershell-commands#data-verbs

But definitely `Format` is the wrong verb: https://docs.microsoft.com/en-us/dotnet/api/System.Management.Automation.VerbsCommon.Format?view=pscore-6.2.0

**Comment by vexx32** [comment]
I dunno about `Convert`. Does this command support bidirectional conversion? Can you put its output back into it and get the original input back?

**Comment by corbob** [comment]
Good point. I don't think the Conversion verbs are a very good fit then. Based on my understanding of what this cmdlet does (which could be wrong), it generates files... The `Convert*` verbs all indicate taking input and outputting something.

And so I think `Invoke` probably fits the bill better... "Performs an action, such as running a command or a method." Build might work if you're targeting PowerShell 6+...

**Comment by timheuer** [comment]
Thanks for the feedback and logging the issue @kilasuit!  This is a utility script mainly used by 2 people, but I appreciate the adherence to good practices.  It's never imported as a module or anything, just manually run by...well, right now mostly me :-).  The original author used this just as a helper and no automation and that remains.  Doesn't mean we shouldn't follow some good guidance, just letting you know the context and priority.
